### ISSUE TITLE
bbswitch not compiling on Fedora 32

### ISSUE THREAD

**Issue by eschruefer** [chenxiaolong/fedora-packages#12]
akmodsbuild --target x86_64 --kernels 5.6.0-0.rc7.git0.2.fc32.x86_64
/usr/src/akmods/bbswitch-kmod.latest
* Rebuilding /usr/src/akmods/bbswitch-kmod.latest for kernel(s)
5.6.0-0.rc7.git0.2.fc32.x86_64: prep build build build
rpmbuild failed with errorcode 1; last 35 Lines of log:
---
+ cp -al bbswitch-0.8 _kmod_build_5.6.0-0.rc7.git0.2.fc32.x86_64
+ RPM_EC=0
++ jobs -p
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.ZCnTMS
+ umask 022
+ cd /tmp/akmodsbuild.49YFjUZu//BUILD
+ cd bbswitch-kmod-0.8
+ for kernel_version in
5.6.0-0.rc7.git0.2.fc32.x86_64___/usr/src/kernels/5.6.0-0.rc7.git0.2.fc32.x86_64
+ make -j8 -C /usr/src/kernels/5.6.0-0.rc7.git0.2.fc32.x86_64
M=/tmp/akmodsbuild.49YFjUZu/BUILD/bbswitch-kmod-0.8/_kmod_build_5.6.0-0.rc7.git0.2.fc32.x86_64
modules
make: Entering directory '/usr/src/kernels/5.6.0-0.rc7.git0.2.fc32.x86_64'
  CC [M] 
/tmp/akmodsbuild.49YFjUZu/BUILD/bbswitch-kmod-0.8/_kmod_build_5.6.0-0.rc7.git0.2.fc32.x86_64/bbswitch.o
/tmp/akmodsbuild.49YFjUZu/BUILD/bbswitch-kmod-0.8/_kmod_build_5.6.0-0.rc7.git0.2.fc32.x86_64/bbswitch.c:
In function 'bbswitch_init':
/tmp/akmodsbuild.49YFjUZu/BUILD/bbswitch-kmod-0.8/_kmod_build_5.6.0-0.rc7.git0.2.fc32.x86_64/bbswitch.c:460:63:
error: passing argument 4 of 'proc_create' from incompatible pointer
type [-Werror=incompatible-pointer-types]
  460 |     acpi_entry = proc_create("bbswitch", 0664, acpi_root_dir,
&bbswitch_fops);
      |                                                              
^~~~~~~~~~~~~~
      |                                                               |
      |                                                              
struct file_operations *
In file included from ./include/acpi/acpi_bus.h:83,
                 from ./include/linux/acpi.h:32,
                 from
/tmp/akmodsbuild.49YFjUZu/BUILD/bbswitch-kmod-0.8/_kmod_build_5.6.0-0.rc7.git0.2.fc32.x86_64/bbswitch.c:32:
./include/linux/proc_fs.h:64:122: note: expected 'const struct proc_ops
*' but argument is of type 'struct file_operations *'
   64 | struct proc_dir_entry *proc_create(const char *name, umode_t
mode, struct proc_dir_entry *parent, const struct proc_ops *proc_ops);
     
|                                                                                                  
~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:268:
/tmp/akmodsbuild.49YFjUZu/BUILD/bbswitch-kmod-0.8/_kmod_build_5.6.0-0.rc7.git0.2.fc32.x86_64/bbswitch.o]
Error 1
make: *** [Makefile:1683:
/tmp/akmodsbuild.49YFjUZu/BUILD/bbswitch-kmod-0.8/_kmod_build_5.6.0-0.rc7.git0.2.fc32.x86_64]
Error 2
make: Leaving directory '/usr/src/kernels/5.6.0-0.rc7.git0.2.fc32.x86_64'
error: Bad exit status from /var/tmp/rpm-tmp.ZCnTMS (%build)


RPM build errors:
    user mockbuild does not exist - using root
    user mockbuild does not exist - using root
    Bad exit status from /var/tmp/rpm-tmp.ZCnTMS (%build)

**Comment by chenxiaolong** [comment]
Thanks, I've included a patch from Arch Linux that should fix this issue.

Commit: https://github.com/chenxiaolong/fedora-packages/commit/cf77adb04d517b98aeb683953a7b76db5135a29c
