### ISSUE TITLE
bbswitch not compiling with kernel 5.7

### ISSUE THREAD

**Issue by eschruefer** [chenxiaolong/fedora-packages#13]
It looks like bbswitch needs an adjustment for kernel 5.7 to compile. ArchLinux seems to have a patch (0002-kernel-5.7.patch) for this already. 
Eberhard

**Comment by chenxiaolong** [comment]
Thanks! Fixed in fdf3a5c55df292280ae60c69192412dbd9bcb918 (published as version `0.8-5` in Copr).
