### ISSUE TITLE
[Feature request] Support for atomic distros

### ISSUE THREAD

**Issue by pm4rcin** [chenxiaolong/fedora-packages#14]
Hi, there are atomic distros like silverblue that doesn't work with new versions because there's the following error when trying to install:

`error: Executing %transfiletriggerin for sbctl: bwrap(/bin/sh)`
and it tells to run journalctl -t 'rpm-ostree(sbctl.transfiletriggerin)' for more information.

```
fedora rpm-ostree(sbctl.transfiletriggerin)[4452]: Generating EFI bundles....
fedora rpm-ostree(sbctl.transfiletriggerin)[4452]: mkdir /var/lib/sbctl: read-only file system
```

https://github.com/Foxboron/sbctl/issues/380 has more details. I've copied the bug report for the most part. I personally use Sway Atomic and it's exactly the same.

**Comment by chenxiaolong** [comment]
Hmm, I'm not sure why `/var` would be mounted read-only when installing with rpm-ostree.

I don't personally use Fedora's atomic distros. It'll probably a while before I have time to set up a VM and try to find a workaround for this.

**Comment by travier** [comment]
I'm not 100% sure what's happening here but on ostree systems, https://github.com/chenxiaolong/fedora-packages/blob/master/copr/sbctl/sbctl/sbctl.spec#L46..L50 will likely not work as you won't have access to the Secure Boot keys during the package layering step.

You can had a check that will skip this step with something like:
```
if [[ -f /run/ostree-booted` ]]; then
	# Do not run on ostree based systems
	return 0
fi
```

**Comment by chenxiaolong** [comment]
> I'm not 100% sure what's happening here but on ostree systems, https://github.com/chenxiaolong/fedora-packages/blob/master/copr/sbctl/sbctl/sbctl.spec#L46..L50 will likely not work as you won't have access to the Secure Boot keys during the package layering step.
> 
> You can had a check that will skip this steps with something like:
> 
> ```
> if [[ -f /run/ostree-booted` ]]; then
> 	# Do not run on ostree based systems
> 	return 0
> fi
> ```

Thanks! I did some reading and it looks like several other packages also do a similar thing.

I suppose it makes sense given `rpm-ostree` is really building an image, and not modifying the current state of the host. I'll update the package after work today to disable that scriptlet on ostree systems.

**Comment by chenxiaolong** [comment]
Sorry for the delay. I wanted to be able to test this on a real system first.

0.16-2 is now available, which disables the file trigger scriptlet on ostree systems.
