### ISSUE TITLE
Rebuild kmod-bbswitch against new kmodtools

### ISSUE THREAD

**Issue by garyedwards** [chenxiaolong/fedora-packages#6]
Hi

It would be great if the `kmod-bbswitch` package could be rebuilt against the new kmodtools to make it work with Silverblue.  This would allow for power saving on laptops when used with the rpmfusion Nvidia drivers:

https://blogs.gnome.org/alexl/2019/03/06/nvidia-drivers-in-fedora-silverblue/

**Comment by garyedwards** [comment]
I have tested it locally and it builds and runs great on Silverblue 30 with no modifications.  I guess it is just triggering a rebuild on the fedora infrastructure.

**Comment by chenxiaolong** [comment]
Thanks for the heads up. I'll rebuild the package for Fedora 30.

**Comment by chenxiaolong** [comment]
Should be good to go: https://copr.fedorainfracloud.org/coprs/chenxiaolong/bumblebee/build/911727/

**Comment by garyedwards** [comment]
Great, I have moved over to your builds and it is working great on SB30.  Thanks.
